spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agro_report
    username: agro_report
    password: agro_report
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/local-public.pem
