spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: agro_deliveries
    password: agro_deliveries
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/local-public.pem
