spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/agro_audit
    username: agro_audit
    password: agro_audit
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/local-public.pem
